services:
  mediamtx:
    container_name: mediamtx
    image: bluenviron/mediamtx:latest-ffmpeg
    restart: unless-stopped
    ports:
      - '9997:9997'
      - '8554:8554'
      - '1935:1935'
      - '8888:8888'
      - '8889:8889'
      - '8890:8890'
    volumes:
      - $PWD/conf:/conf:ro
    command: /conf/mediamtx.yml
